providers:
  mino:
    minoUrl: 'http://115.28.105.227:8888'
    accessKey: 'minioadmin'
    secretKey: 'minioadmin'
    bucketName: 'blog'
#spring:
#  data:
#    elasticsearch:
#    host: localhost
#    port: 9300
#    cluster:
#      name: elasticsearch
#spring:
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      #节点的地址，注意api模式下端口号是9300，千万不要写成9200
#      #是否开启本地存储
#      repositories:
#        enabled: false
#      cluster-nodes: localhost:9300
spring:
  redis:
    host: "115.28.105.227"
#    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-idle: 8
        max-active: 32
        max-wait: "3000"
        min-idle: 4
    password: "135799"
    timeout: "30000"







